language: python
python:
  - "2.7"

cache: pip

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)

install: 
  - 'pip install -r requirements.txt'

#run tests
script: 
  - python ./test/flask_test.py